

spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch-cluster
      cluster-nodes: 172.16.134.98:9300,172.16.134.98:9301,172.16.134.98:9302



logging:
  level:
    root: info
    org.apache.kafka: error
server:
  port: 10080

