spring:
  datasource:
    url: jdbc:mysql://mall.jenkin.tech:7307/log_platform?setUnicode=true&characterEncoding=utf8
    username: root
    password: Zhoujin@Zcr0807
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
    database: mysql
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  main:
    allow-bean-definition-overriding: true

server:
  port: 8705
  tomcat:
    connection-timeout: 1200000
